version: '3'
services:
  DDZookeeper:
    image: "confluentinc/cp-zookeeper:latest"
    ports:
      - "32181:32181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
    restart: always
    networks:
      - "dd-net"
  DDKafka:
    image: "confluentinc/cp-kafka:latest"
    ports:
      - "39092:39092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "DDZookeeper:32181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://DDKafka:39093,PLAINTEXT_HOST://localhost:39092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_BROKER_ID: 1
    networks:
      - "dd-net"
  KSQL:
    image: "confluentinc/cp-ksql-server:latest"
    ports:
      - "8088:8088"
      - "8089:8089"
    environment:
      KSQL_BOOTSTRAP_SERVERS: "DDKafka:39093"
      KSQL_LISTENERS: "http://0.0.0.0:8088/,https://0.0.0.0:8089/"
    networks:
      - "dd-net"
#  DDKafka2:
#    image: "confluentinc/cp-kafka:latest"
#    ports:
#      - "49092:49092"
#    environment:
#      KAFKA_ZOOKEEPER_CONNECT: "DDZookeeper:32181"
#      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://DDKafka2:39093,PLAINTEXT_HOST://localhost:49092"
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
#      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_BROKER_ID: 2
#    networks:
#      - "dd-net"
networks:
  dd-net: